version: '3.4'

services:
  generator:
    build:
      context: generator/.
    environment:
      - WRITERS=4
      - VALIDATORS=3
    volumes:
      - ./volumes/validators:/validators
      - ./volumes/writers:/writers

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: latest
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    entrypoint: /opt/besu/bootnode_start.sh
    command: &base_options [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=WEB3,ETH,NET,IBFT,ADMIN",
      "--rpc-ws-api=WEB3,ETH,NET,IBFT,ADMIN",
    ]
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/bootnode/keys:/opt/besu/keys
      - ./volumes/bootnode/data:/opt/besu/data
    depends_on:
      - generator
    networks:
      lacchain:
        ipv4_address: 172.24.2.2

  validator1:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/validators/1/keys:/opt/besu/keys
      - ./volumes/validators/1/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.11

  validator2:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/validators/2/keys:/opt/besu/keys
      - ./volumes/validators/2/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.12

  validator3:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/validators/3/keys:/opt/besu/keys
      - ./volumes/validators/3/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.13

  writer1:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/writers/1/keys:/opt/besu/keys
      - ./volumes/writers/1/data:/opt/besu/data
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp
    networks:
      lacchain:
        ipv4_address: 172.24.2.51

  writer2:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/writers/2/keys:/opt/besu/keys
      - ./volumes/writers/2/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.52

  writer3:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/writers/3/keys:/opt/besu/keys
      - ./volumes/writers/3/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.53

  writer4:
    image: lacchain-network/besu:latest
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
    command: *base_options
    volumes:
      - ./:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/genesis.json:/config/genesis.json
      - ./volumes/writers/4/keys:/opt/besu/keys
      - ./volumes/writers/4/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      lacchain:
        ipv4_address: 172.24.2.54

  explorer:
    build: explorer/.
    image: lacchain-network/block-explorer-light:latest
    depends_on:
      - writer1
    ports:
      - 25000:80/tcp
    networks:
      lacchain:
        ipv4_address: 172.24.2.254

networks:
  lacchain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.2.0/24
